[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings=['@chainlink/contracts-ccip/=lib/ccip/contracts/','aave-v3-core/=lib/aave-v3-core/','gho-core/=lib/gho-core/','@openzeppelin/=lib/openzeppelin-contracts/','@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/']


[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
# forge install smartcontractkit/ccip@ccip-develop